temp <- tempfile()
download.file("http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp, mode = "wb")
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
unlink(temp)
data$Date <- as.Date(data$Date, "%d/%m/%Y")
png(filename = "plot1.png")
cleansubset <- subset(data, Date>="2007-02-01" & Date<="2007-02-02")
with(cleansubset, hist(Global_active_power, col = "red",main = "Global Active Power", xlab = "Global Active Power (kilowatts)"))
dev.off()