temp <- tempfile()
download.file("http://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp, mode = "wb")
data <- read.table(unz(temp, "household_power_consumption.txt"), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
unlink(temp)
data$DateTime <- strptime(paste(data$Date, data$Time, sep = " "),format="%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
datesubset <- subset(data, Date>="2007-02-01" & Date<="2007-02-02")
png(filename = "plot3.png")
with(datesubset, plot(DateTime, Sub_metering_1, type="l", xlab="", ylab = "Energy sub metering"))
with(datesubset, lines(DateTime, Sub_metering_2, col = "red", type="l"))
with(datesubset, lines(DateTime, Sub_metering_3, col = "blue",type="l"))
legend("topright", pch = "", col = c("black", "red","blue"), lwd=1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()